### PR TITLE
Gives access to three activation choices

### PR DESCRIPTION
**Pull request by Arubinu**
Thank you for accepting my previous request.

This time I added options that allow you to choose whether you want the timeout to be suspended or reset in certain situations.

- mouse_move: when moving the mouse
- mouse_click: on mouse click
- in_lovelace: only on Lovelace views

### CODE REVIEW

**Comment by BWilky** [comment]
Thanks for your contributions! Just skimming through this quickly. I like the reset ideas. What would be a situation for the in_lovelace?

**Comment by Arubinu** [comment]
😁 In fact it's the opposite of the others.  This allows you not to redirect to the view, if you are in the settings, the energy panel, or any other place than the lovelace dashboards.

**Comment by Arubinu** [comment]
I'm in the process of managing views, it's going to take a little time but I think it will make this tool complete 😄

**Comment by Arubinu** [comment]
I took the liberty of making certain modifications without distorting the original code.

Hoping that you like it.
I put a `console.info` like the other Lovelace resources do, to specify the version (and I put v1.1.0).

**Comment by BWilky** [comment]
Looks Good! Thanks, happy holidays

**Pull request merged**
